/*
 * This source file was generated by the Gradle 'init' task
 */
package budget.application;

import budget.application.db.util.DataSourceFactory;
import budget.application.db.util.DatabaseHealthCheck;
import budget.application.server.core.ServerNetty;
import budget.application.utilities.Constants;
import budget.application.utilities.ScheduleManager;
import io.github.bibekaryal86.shdsvc.helpers.CommonUtilities;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.sql.DataSource;
import lombok.extern.slf4j.Slf4j;

@Slf4j
public class Main {

  public static void main(String[] args) throws Exception {
    log.info("Starting Budget Service...");
    Main.checkEnvProperties();

    DataSource dataSource = DataSourceFactory.create();

    var dbHealth = new DatabaseHealthCheck(dataSource).check();
    log.info("{}", dbHealth);

    ServerNetty serverNetty = new ServerNetty(dataSource);
    serverNetty.start();

    ScheduleManager schedulerManager = new ScheduleManager(dataSource);
    schedulerManager.start();

    Runtime.getRuntime()
        .addShutdownHook(
            new Thread(
                () -> {
                  log.info("Shutdown initiated...");
                  try {
                    schedulerManager.shutdown();
                  } catch (Exception e) {
                    log.error("Error shutting down scheduler... ", e);
                  }
                  try {
                    log.info("Stopping Netty server...");
                    // TODO
                  } catch (Exception e) {
                    log.error("Error stopping Netty server... ", e);
                  }
                  log.info("Shutdown complete...");
                },
                "shutdown-hook"));

    log.info("Started Budget Service...");
  }

  private static void checkEnvProperties() {
    final List<String> envKeyNames = new ArrayList<>(Constants.ENV_KEY_NAMES);

    if (Constants.IS_PRODUCTION) {
      envKeyNames.addAll(Constants.ENV_KEY_NAMES_PROD);
    } else {
      envKeyNames.addAll(Constants.ENV_KEY_NAMES_SANDBOX);
    }

    final Map<String, String> properties = CommonUtilities.getSystemEnvProperties(envKeyNames);
    final List<String> requiredEnvProperties =
        envKeyNames.stream().filter(key -> !Constants.ENV_SERVER_PORT.equals(key)).toList();

    final List<String> errors =
        requiredEnvProperties.stream().filter(key -> properties.get(key) == null).toList();
    if (!errors.isEmpty()) {
      throw new IllegalStateException(
          "One or more environment configurations could not be accessed...");
    }
  }
}
