/*
 * This source file was generated by the Gradle 'init' task
 */
package budget.application;

import budget.application.common.Constants;
import io.github.bibekaryal86.shdsvc.helpers.CommonUtilities;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Main {
  private static final Logger log = LoggerFactory.getLogger(Main.class);

  static void main(String[] args) throws Exception {
    log.info("Starting Budget Service...");
    Main.checkEnvProperties();
    AppContext appContext = new AppContext();

    appContext.scheduleManager.start();
    appContext.serverNetty.start();

    Runtime.getRuntime()
        .addShutdownHook(
            new Thread(
                () -> {
                  log.info("Shutdown initiated...");
                  try {
                    appContext.scheduleManager.shutdown();
                  } catch (Exception e) {
                    log.error("Error shutting down scheduler... ", e);
                  }
                  try {
                    appContext.serverNetty.stop();
                  } catch (Exception e) {
                    log.error("Error shutting down server... ", e);
                  }
                  log.info("Shutdown complete...");
                },
                "shutdown-hook"));

    log.info("Started Budget Service...");
  }

  private static void checkEnvProperties() {
    final List<String> envKeyNames = new ArrayList<>(Constants.ENV_KEY_NAMES);

    if (Constants.IS_PRODUCTION) {
      envKeyNames.addAll(Constants.ENV_KEY_NAMES_PROD);
    } else {
      envKeyNames.addAll(Constants.ENV_KEY_NAMES_SANDBOX);
    }

    final Map<String, String> envProperties = CommonUtilities.getSystemEnvProperties(envKeyNames);
    final List<String> requiredEnvProperties =
        envKeyNames.stream().filter(key -> !Constants.ENV_SERVER_PORT.equals(key)).toList();

    final List<String> errors =
        requiredEnvProperties.stream().filter(key -> envProperties.get(key) == null).toList();
    if (!errors.isEmpty()) {
      throw new IllegalStateException(
          "One or more environment configurations could not be accessed...");
    }
  }
}
